### ISSUE TITLE
Gas guidance

### ISSUE THREAD

**Issue by ethers** [sikoba/token-presale#12]
Maybe worth mentioning some recommended gas value (tests use 100,000) since fallback function is used (as well as in case there are contracts or contract wallets that use `send()`
https://github.com/ConsenSys/smart-contract-best-practices#keep-fallback-functions-simple).

**Comment by sikoba** [comment]
Thank you Ethers! 

Gas used is below the 90,000 gas that contract use.

Past empirical data by our consultant Bok Pah has shown very little contract interaction with `send()` for example with *theDao*

> Bokky Poobah: If you download https://github.com/bokkypoobah/TheDAOData/blob/master/CreatedTokenEventsWithNonZeroExtraBalance_v4.xlsx and place a filter in the column B to only view "Wallet Contract", you will see many contributions to The DAO extraBalance account from multisig contracts. The amount of gas used is displayed in L. This call was to the fallback function and it consumed gas larger than 2,300 or 90,000, e.g. 109304 .

**Comment by rolandkofler** [comment]
Not an issue as it is not intendet to be called by other contracts `.send()`.
